### ISSUE TITLE
Switching default branch to 'main'

### ISSUE THREAD

**Issue by paytonagreen** [gardenbuilder-app/gardenbuilder-frontend#55]
## Type
Changing terminology to respect inclusivity

## Problem or To-Do
In response to concerns from the Black community, it seems to be good practice to change the default branch of a project to 'main' rather than 'master'. I think in line with our principles we should make the move! I've created a 'main' branch which is currently even with 'master'.

**Comment by capndave** [comment]
@paytonagreen closing as this is done, thanks!
